version: "3"
services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace
      - node-module-volume:/workspace/node_modules
    ports:
      - 3000:3000
    command: ["yarn", "dev"]
volumes:
  node-module-volume:
